# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d71be539a08335b85110a9bdfb70c6fd6339003b595b7e8480e6b0f4acddeea85bc45932e6b569f5dd6395df09567462d3511b568ce55d1fc0fffd15ff0c06f

test:
  secret_key_base: 90dd98c491a5b789752126b2ecfe77b6ff3602791a074bb43d111704f62797b209db4a15097db34c29267184bc113adc1c4822a698e61ade959685fe3e712be5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
